### ISSUE TITLE
Jquery problem

### ISSUE THREAD

**Issue by wijagels** [autodl-community/autodl-rutorrent#10]
On the latest rutorrent build, the autodl plugin tries to use a removed jquery function, consequently spamming the console with this message:

    AutodlIrssiTab._getNewLines: Exception info: name = TypeError; message = Cannot read property 'msie' of undefined;

There is a temporary fix, you can load up the jquery-migrate file with this line in index.html:

    <script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>

**Comment by thebigmunch** [comment]
This is a duplicate issue.
