### ISSUE TITLE
Move Announce Channels from menu to IRC Servers dialog

### ISSUE THREAD

**Issue by thebigmunch** [autodl-community/autodl-rutorrent#13]
The Announce Channels menu is full of good intentions. The problem is that it seems to confuse more people than actually make use of it. Most people get the IRC info they need from tracker sites themselves.

So, I'd like to simply remove it. But first, I'd like to see if anyone out there really cares about it or find it useful enough to keep.

**Comment by OoGuru** [comment]
I think it's nice - not all tracker site have easy accessible information like that little menu :)

**Comment by flier56** [comment]
i would like to keep it i think it is very useful

**Comment by DjLegolas** [comment]
i think it will be better to just rename to something else. this way it won't be confusing.

**Comment by anonaut** [comment]
I am in favor of just renaming. I had it once already that I join a site
and their irc faq is wrong/old and I could just look into the announce
channel menu and had the right data.

**Comment by thebigmunch** [comment]
Any thoughts of what to rename it.

Also, what about moving it into the IRC Servers dialog as some kinda help/info link/button?

**Comment by OoGuru** [comment]
It would make sense to have it in the IRC servers menu so that you don't have to switch between the Announce Channel menu and IRC server menu to check the information - I am just wondering if there is enough space for it, or if you have some smart non-intrusive way of handling having an extra button in there.

**Comment by DjLegolas** [comment]
Maybe adding a new button next to "New" and "Remove", which will open the Announce Channels menu? 
Both are related and this way one could check the info without having to close the IRC Servers menu to enter the Announce Channels.

**Comment by thebigmunch** [comment]
Yeah, it could be as simple as this:

![Announce Channels](http://waa.ai/vkXO)
