### ISSUE TITLE
Minor code bug in autodl-irssi.css

### ISSUE THREAD

**Issue by glorpsd** [autodl-community/autodl-rutorrent#14]
autodl-irssi.css:

#autodl-multiselect-header {
        background-image: url("../../images/settings.gif");
}

should be

#autodl-multiselect-header {
        background-image: url("../../../images/settings.gif");
}

moving the css into a subdrectory made the relative path back to the main rutorrent app images invalid. Can't see that settings.gif is even needed or makes a difference but it throws errors in the apache logs every time the rutorrent gui is accessed.

**Comment by thebigmunch** [comment]
Yup, missed that one. It's just the little icon next to the window titles.
