### ISSUE TITLE
ssl not staying checked in server window

### ISSUE THREAD

**Issue by flier56** [autodl-community/autodl-rutorrent#15]
in the autodl-irssl IRC Server window the ssl tick will not stay checked
 in autodl.cfg shows ssl = true. was working before last update

**Comment by thebigmunch** [comment]
I can't replicate the issue. Make sure you don't have duplicate ssl options set or multiple headers for the same server.

**Comment by flier56** [comment]
don't see any duplicate ssl options, revolutiontt is the site i am having problems with under trackers force ssl is checked

**Comment by maphex** [comment]
having the same issues but for me

**Comment by Neonlinx** [comment]
Same issue here. And I can't join announce channel except What.cd. In the log seems to work but: nick identified, invite command sent...but it stops when sending join command on #announce channel (then starts to try every tot seconds with no success). This happens for BeatHau5 and Waffles. I'm using Ubuntu 14, autodl-irssi is updated, apache2, rtorrent/libtorrent 0.9.4/0.13.4, rutorrent 3.6. Also What.cd  did not work. So i updated (manually) the plugin and starts to work. Maybe a problem with ssl (tracker side)?? 

Thanks anyway

**Comment by ne0ark** [comment]
This has happened to me also. I believe it has to do with web browser.

**Comment by Neonlinx** [comment]
I try with an other managed seedbox and it works without any problem. So (almost in my case) I think the problem is caused by some not-update modules (like pyhton or others) from my side. Infact I'm using a dedicated server (Kimsufi/OVH) and sincerly I'm not so skilled with linux. I'm using python 2.7.6.....maybe do I need to update to 2.7.10??

**Comment by Neonlinx** [comment]
EDIT:

Updateed python to 2.7.10 and now it works perfect. Only the tick on ssl box still not works but the connection is on ssl.

Thanks anyway!

**Comment by thebigmunch** [comment]
Closing because there's no evidence this is an issue within autodl-rutorrent itself. If anyone finds anything to the contrary, please post here.
