### ISSUE TITLE
SslSocket.pm fails with no error

### ISSUE THREAD

**Issue by vprong** [autodl-community/autodl-rutorrent#16]
Line:
$self->{ssl} = Net::SSLeay::new($AutodlIrssi::g->{ssl_ctx}) or die "Could not create SSL\n";

In AutodlIrssi/SSlsocket.pm was failing with a misleading "connection timed out" being printed to the irssi console. I ran/put in all kinds of packet captures and firewall rules to determine the connection attempt never actually occurred. The issue was resolved by installing Net::SSLeay 1.69 instead of Centos 6.6 default yum repo version 1.35.

Version 1.35 did not have have any ssl_ctx related options. Would save someone a lot of grief to do a version check on this module.

**Comment by thebigmunch** [comment]
This has nothing to do with the ruTorrent plugin and has been discussed in other places. I don't really feel the need to cater to people who don't keep their systems reasonably updated. Versions of Net::SSLeay and OpenSSL supporting SNI have been released for at least 2 years now. And the change to add SNI support in autodl-irssi was made in a release nearly 2 months ago.
