### ISSUE TITLE
autodl-irssi error

### ISSUE THREAD

**Issue by gekioo** [autodl-community/autodl-rutorrent#19]
Hello guys, 
I don't have any experience with linux commands and I hope that someone can help me with this problem.
I have a dedicated seedbox and I want to install autodl-irssi community.
I opened a ticket and they answered that they don't offer support for that and I should do it by my self through SSH access. I searched for a tutorial and launched putty and started typing the commands from the tutorial. Those are the commands that I used:

mkdir -p ~/.irssi/scripts/autorun ~/.autodl
echo -e "[options]\ngui-server-port = 0\ngui-server-password = PASS" > ~/.autodl/autodl.cfg
wget -qO ~/autodl-irssi.zip http://update.autodl-community.com/autodl-irssi-community.zip
unzip -qo ~/autodl-irssi.zip -d ~/.irssi/scripts/
cp -f ~/.irssi/scripts/autodl-irssi.pl ~/.irssi/scripts/autorun/
cd && rm -f autodl-irssi.zip .irssi/scripts/{README*,autodl-irssi.pl,CONTRIBUTING.md}

nano ~/.autodl/autodl.cfg

![1](https://cloud.githubusercontent.com/assets/15219712/10619656/2794c828-7777-11e5-87bd-83a2e68b0a9c.png)

I chose a port and a password, then I typed those commands:

cd /home/myusername/www/rutorrent/plugins/
wget -qO autodl-rutorrent.zip https://github.com/autodl-community/autodl-rutorrent/archive/master.zip
unzip -qo autodl-rutorrent.zip
cp -rf autodl-rutorrent-master/. autodl-irssi
rm -rf autodl-rutorrent.zip autodl-rutorrent-master
cp -f autodl-irssi/_conf.php autodl-irssi/conf.php
nano autodl-irssi/conf.php

![2](https://cloud.githubusercontent.com/assets/15219712/10619673/3f01c3b2-7777-11e5-944b-a5790a4b9cc5.png)

And I typed the same port and password in the "conf.php",, Then I continued with these commands

screen -dmS autodl irssi
screen -r autodl

And I pressed (ctrl+a) and then pressed "d"

"autodl-irssi" Was installed when I launched rutorrent but I'm getting this error "JS error: [http://**********************************************/rutorrent/plugins/autodl-irssi/js/AutodlIrssiTab.js : 62] Uncaught TypeError: elem.prop is not a function

I replaced the info in the beginning with *

How can I fix this problem? I'm sorry for making my post long but I wanted to explain everything I did so I can get help if anything was wrong.
Is it because the commands were not correct? I don't have any experience and I would like to get help with this. 
Thanks

**Comment by thebigmunch** [comment]
Support problems like this should be taken to the IRC channel, not posted on the issue tracker. But it's probable that you're using an old version of ruTorrent.

**Comment by thebigmunch** [comment]
For the record, this was caused by his provider (PulsedMedia) installing an incredibly old version of ruTorrent (3.4) on their seedboxes.
