### ISSUE TITLE
Error when starting plugin after version upgrade

### ISSUE THREAD

**Issue by glorpsd** [autodl-community/autodl-rutorrent#21]
So I just installed the new version of autodl-rutorrent onto an existing seedbox. I removed the old autodl-irssi plugin directory then grabbed the updated version's .zip file, unzipped, changed permissions/ownership of files to match what had been used before, and copied my saved conf.php file back from a backup I made of the old version's plugin directory. Started up rutorrent and this is the error I get:

autodl-irssi: __init2: ex: Exception info: name = ReferenceError; message = installEmptyTextHandlers is not defined; fileName = https://<edited for privacy>/rutorrent/plugins/autodl-irssi/js/Preferences.js; lineNumber = 307; 

and the autodl plugin does not load at all in rutorrent.

I revert all the changes and restore a saved copy of the old version of the plugin's directory I made before starting. Old version starts again, no errors.

This is the result from "/autodl version" run from the irssi commandline:
14:12 -!- Irssi: You are running autodl-irssi v1.61 | autodl-trackers v252

?

**Comment by thebigmunch** [comment]
You messed something up in installing the ruTorrent plugin; that line no longer exists : )

**Comment by glorpsd** [comment]
Huh? It's right here:

Line 307 of Preferences

**Comment by glorpsd** [comment]
What?

It's right here: Line 307 of rutorrent/plugins/autodl-irssi/js/Preferences.js
307: Preferences.prototype.onBeforeShow =

Looks like something to do with code running in an event handler called before the UI shows. Probably not initializing an added variable since I have an existing installation? Dunno.

**Comment by thebigmunch** [comment]
https://github.com/autodl-community/autodl-rutorrent/blob/master/js/Preferences.js#L307 <-- It's really not. There is no installEmptyTextHandlers on that line like there used to be. There is no installEmptyTextHandlers inside that function or anywhere else in the code anymore. You can search the repo if you don't believe me.
