### ISSUE TITLE
Undefined Section in Filters

### ISSUE THREAD

**Issue by bjay1404** [autodl-community/autodl-rutorrent#22]
Hello - I'm having some issues with the Filters Tab - The second tab on a filter says undefined and there are a number of sections such as match releases that shows up as undefined. Any tips? I'm on 1.61

**Comment by thebigmunch** [comment]
What language is set in ruTorrent settings? What theme?

**Comment by bjay1404** [comment]
English and the Standard Theme

**Comment by thebigmunch** [comment]
I can't reproduce this. I'd reinstall the plugin from scratch to see what happens.

**Comment by bjay1404** [comment]
I tried that and it didn't help.  Also for tv shows should I have the name
under match releases or tv show?

**Comment by bjay1404** [comment]
Okay, I updated the plugin. I must have done something wrong last time. Anyway - Let's say I'm looking for a TV Show. Will this config work? I wasn't sure what the syntax for TV Shows vs Match-Releases? What's the best way to do this? 

 [filter The Flash]
 match-sites = btn
 resolutions = 720P
 encoders = x264
 max-downloads = 1
 rt-dir = /media/640/p/rtorrent/download/sickbeard
 rt-label = autodl
 upload-type = rtorrent
 max-downloads-per = week
 rt-ratio-group = rat_3
 seasons = 2
 match-release-groups = DIMENSION
 except-releases = HDTV.DD.5.1
 match-releases = The?Flash?2014*

**Comment by thebigmunch** [comment]
The Issue tracker is not for support. Go to the IRC channel for that.
