### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by bjay1404** [autodl-community/autodl-rutorrent#23]
In reference to my earlier issue : https://github.com/autodl-community/autodl-rutorrent/issues/22#issuecomment-185796049

Everything was working fine after a fresh install of the plugin. I managed to get a test filter working. The undefined error went away - leaving me with this error.

autodl-irssi: __init2: ex: Exception info: name = ReferenceError; message = installEmptyTextHandlers is not defined;

Thank you for the earlier help!

**Comment by thebigmunch** [comment]
You're not installing the latest version.
