### ISSUE TITLE
Error After Updating to 1.62

### ISSUE THREAD

**Issue by Pingblue** [autodl-community/autodl-rutorrent#24]
Since upgrading to 1.62 I have this error in the log

`autodl-irssi: __init2: ex: Exception info: name = ReferenceError; message = installEmptyTextHandlers is not defined; fileName = 192.168.1.0/rutorrent/plugins/autodl-irssi/js/Preferences.js; lineNumber = 307; `

**Comment by thebigmunch** [comment]
Something didn't go right with your update. The code the error says is on that line has been gone for quite some time now.
