### ISSUE TITLE
missing tab and icon

### ISSUE THREAD

**Issue by SirPirate** [autodl-community/autodl-rutorrent#29]
Hi @thebigmunch 
today I installed autodl-irssi and autodl-rutorrent. Autodl-irssi works fine! When I run irssi I don't have any issue and everything is fine, but problem appears in rutorrent with autodl-rutorrent. I do not have autodl icon and autodl tab. In plugins tab I have [ Name: autodl-irssi / Status: Loaded / Launch: Enabled ]. Moules I also have.  Only one I not added extension=sockets.so extension=json.so extension=xml.so to /etc/php5/apache2/php.ini, becouse I dont know where to add it (before or after end of file) 

libtorrent-0.13.6
rtorrent-0.9.6
ruTorrent 3.7
autodl-irssi v1.62

**Comment by thebigmunch** [comment]
This isn't a place for support. It looks to be a problem with something on your system, not autodl-rutorrent.
