### ISSUE TITLE
self-signed SSL certificate with autodl-rutorrent

### ISSUE THREAD

**Issue by fromptoz** [autodl-community/autodl-rutorrent#30]
I use self-signed SSL certificate instead of password for protection of rutorrent connection
While when I set up autodl-rutorrent, it asks offering rutorrent's gui-server port and password to function normally,
Is there any other way to set up autodl-rutorrent with self-sighned SSL certificate?

**Comment by thebigmunch** [comment]
The gui-server port and password has nothing to do with ruTorrent. It is autodl-ruTorrent's way of connecting to autodl-irssi on the localhost.

Also, an SSL cert is not an alternative to password protection for anything. They do separate things.
