### ISSUE TITLE
autodl-irssi: __init2: ex: Exception info: name = ReferenceError; message = installEmptyTextHandlers is not defined;

### ISSUE THREAD

**Issue by ormanya** [autodl-community/autodl-rutorrent#32]
The following error occurs when refreshing rutorrent after re-installing the plugin:
autodl-irssi: __init2: ex: Exception info: name = ReferenceError; message = installEmptyTextHandlers is not defined;

Prior to reinstalling I deleted the rutorrent/plugins/autodl-irssi directory. I then followed the instructions in the README for reinstalling.

**Comment by thebigmunch** [comment]
I'm not sure what you've done wrong, but ``installEmptyTextHandlers`` hasn't been part of any code in this plugin for over 1 1/2 years. I'm afraid I can't really provide any help beyond that.

**Comment by ormanya** [comment]
For anyone else experiencing this issue after update, turns out my browser was caching some files from the old version. Clearing cache solved the problem.
