### ISSUE TITLE
feature request: clone/ copy a filter

### ISSUE THREAD

**Issue by baz357** [autodl-community/autodl-rutorrent#33]
Instead of always having to start from zero with a new filter, wouldn't it be great if one could just clone an existing filter and just edit it a bit? Would be faster and more comfortable than grabbing the autodl.cfg, editing it, and putting it back.

In the Filters window, next to "New" and "Remove", a new "Copy" button would copy the current filter, name it "Copy of [current filter name]", and maybe disable the copy by default.

Thanks to everyone working on autodl-irssi!

**Comment by thebigmunch** [comment]
Should be good to go. Check it out.

**Comment by baz357** [comment]
My seedbox provider is still using the 1.65 version, so maybe I'll have to wait for 1.66 to be able to check it out. :-/
