### ISSUE TITLE
Add zero-configuration code to getConf 

### ISSUE THREAD

**Issue by flier56** [autodl-community/autodl-rutorrent#35]
after this latest update to getConf.php receive this error 
[10/11/2017 15:34:26] Error downloading files. Make sure autodl-irssi is started and configured properly (eg. password, port number): Could not get files listing: AJAX error, status: error, Exception info: Internal Server Error
replace with  getConf.php before update error goes away and autodl-rutorrent works again

**Comment by anthonyryan1** [comment]
Hello flier56,

Sorry about that, I'm quite certain this is my fault and I've identified the cause. Could you kindly confirm that this version of getConf https://raw.githubusercontent.com/anthonyryan1/autodl-rutorrent/b6dfe8a4cf019fb4c53f9b00be313fec864fb93f/getConf.php resolves the issue for you?

**Comment by flier56** [comment]
that fixed the problem thanks for great work
