### ISSUE TITLE
Missing PHP module: xml

### ISSUE THREAD

**Issue by kade-robertson** [autodl-community/autodl-rutorrent#41]
Strangely, `GetPhpModules()` is returning that the xml module is missing. It has never done this until a few days ago.

`for module in json xml sockets; do php -m|grep -wq $module || echo "Missing module: $module"; done` outputs nothing.

apache2 and autodl-irssi have been restarted multiple times.

`php.ini` contains `extension=xml.so` uncommented.

If I run the following:
```php
<?php
require_once 'getConf.php';
GetPhpModules();
```

nothing is echoed. It is only in the context of being run from ruTorrent. However nothing should have changed on my system to prevent this from working.

**Comment by thebigmunch** [comment]
> However nothing should have changed on my system to prevent this from working.

Most of the time people say this, something changed or they changed something.

Also, there doesn't seem to be a bug report here. It looks like it's almost certainly something specific to your setup. You won't find help here fixing or properly setting up your system.
