### ISSUE TITLE
v2.3.0: SSL enabled but shown as disabled (IRC Servers -> server settings)

### ISSUE THREAD

**Issue by baz357** [autodl-community/autodl-rutorrent#42]
When you go to IRC Servers -> server settings -> and enable SSL for a server, confirm with OK and then open the same settings again, SSL is being shown as disabled (the checkmark is missing).

But by using the Backup option you'll find that SSL is still enabled. It's just the checkmark that's missing in the UI.

**Comment by thebigmunch** [comment]
Something similar has been brought up [before](https://github.com/autodl-community/autodl-rutorrent/issues/15). I've never been able to reproduce that. And I can't reproduce this. Most likely system-specific and not an issue with autodl-rutorrent. But, if you can find otherwise, please let me know.
