### ISSUE TITLE
Wanting to inject code that launches a script...

### ISSUE THREAD

**Issue by SteveMalso** [autodl-community/autodl-rutorrent#46]
Hey,

I'm not much of a coder but I'm wanting to insert a line of code that calls a bash script that reads my available hard drive space and deletes files if it's 90% full.  I would like to launch this script just before your addon sends the torrent file/link to rtorrent. 

I would really appreciate it if you could advise me on the line and file I need to insert my code that will launch a bash script.

Thank you

**Comment by thebigmunch** [comment]
It would be in autodl-irssi, not autodl-rutorrent. And no, you'll need to figure out where to do this on your own. Or you can just use the exec torrent action to run a script that does what you want.
