### ISSUE TITLE
Cyclying through servers overwrites checkboxes BNC & SSL

### ISSUE THREAD

**Issue by Kodelak** [autodl-community/autodl-rutorrent#47]
When opening the Autodl-irssi  IRC Servers window inside rutorrent. If you cycle through all the servers that contain checkboxes marked as true, meaning SSL and BNC are active, nothing is affected all settings remain the same. Once you select one server that does NOT have the checkmarks enabled, and you go back to another server that previously had checkboxes set to True, they are no longer set to true.  If you keep cylcing through the servers eventually all will lose their checkmarks. In order to restore them other than manually uploading the proper config file, is to set 1 server with BNC and SSL enabled and then select the next and select it as well, you cannot go to a non ssl and bnc and then go to one you previously set otherwise settings will be lost again.

**Comment by thebigmunch** [comment]
I can't reproduce this. Previous checkbox issues seemed to be a result of older jQuery versions, so you could start there with debugging (assuming current autodl-rutorrent version is being used). But, if I can't reproduce it, I can't do anything to fix it.

**Comment by Kodelak** [comment]
checking at ~/rutorrent/js/jquery.js   I see    /*! jQuery v1.12.4 .   But this might be specific to my box as you mentioned, Initially thought it could be browser autofill related as I had that issue in the past, but inprivate browsing with Chrome and IE resulted in the same.

**Comment by thebigmunch** [comment]
I'm testing it on that jQuery version now, too. But I still can't reproduce.
