### ISSUE TITLE
ruTorrent 3.8 + Oblivion Theme + autodl-irssi Filters window

### ISSUE THREAD

**Issue by baz357** [autodl-community/autodl-rutorrent#48]
My account was updated from ruTorrent 3.7 to ruTorrent 3.8 today. Now the autodl-irssi Filters window doesn't show properly* unless I increase the window zoom in Chrome to 150%. Not sure if the cause is ruTorrent or autodl-irssi (which already was up to date).

*The "General | P2P | TV/Movies..." bar is shown at the bottom of the autodl-irssi Filters window:

![screenshot - 2018-11-07](https://user-images.githubusercontent.com/20575996/48142809-c9f07a00-e2ad-11e8-8c0d-c2d4dcc8de63.png)

**Comment by thebigmunch** [comment]
I can't reproduce it here with Chrome and ruTorrent 3.8.

**Comment by baz357** [comment]
Hmm... weird. Are you using the Oblivion theme? It doesn't happen with other themes, but I only like the Oblivion theme. :)
