### ISSUE TITLE
Newly created filters should be inactive

### ISSUE THREAD

**Issue by nokatt** [autodl-community/autodl-rutorrent#49]
I accidentally hit the "New" button in filters without noticing it. That created an empty filter and every torrent of my active trackers were downloaded. Luckily it didn't do much damage.
I propose to make newly created filters inactive so this problem doesn't occur by accident.

**Comment by gregsterb** [comment]
You had to have added the trackers to the new filter for it to do anything. So you must be lieing about only hitting new.

**Comment by thebigmunch** [comment]
> You had to have added the trackers to the new filter for it to do anything. So you must be lieing about only hitting new.

Wrong. Not setting trackers will match for all trackers. And don't bring that kind of accusatory attitude here.

------

However, it's definitely a no on making them inactive by default. One, this would only ever be an issue in the ruTorrent plugin, not when editing the config file. This change would force people who manually configure to have to enable every filter they create when not done through the ruTorrent plugin.

If you want things to be extra safe for yourself, simply leave the default action (or manually set to 'Test') globally, so you'll have to set the action for every filter before it will actually download any torrents.
