### ISSUE TITLE
Filter window breaks when WOL tab is clicked

### ISSUE THREAD

**Issue by satcos** [autodl-community/autodl-rutorrent#54]
Filter window goes bank when WOL tab is clicked.
<img width="610" alt="Screenshot 2020-07-13 at 3 06 08 PM" src="https://user-images.githubusercontent.com/7912025/87290317-7838d200-c51b-11ea-81ad-1dc047312efc.png">

**Comment by thebigmunch** [comment]
This issue tracker is for bug reports and feature requests, not support. This isn't happening on any of my browsers for my autodl-rutorrent install. You're probably gonna need to do some digging to find out why it's happening on yours to determine to find out where the problem is caused.
